### ISSUE TITLE
Mirror image to Docker Hub

### ISSUE THREAD

**Issue by tmaier** [elastic/elasticsearch-docker#113]
It is super annoying that the official docker image is not anymore available on Docker Hub.

This means features, like "Repository Links" do now work anymore.
What's that anyway, you may ask?
> Link your Automated Build to another Docker Hub repository, and when that repository is updated, it will automatically trigger a rebuild of this Automated Build.

This means my docker images, which take the elasticsearch image as base image, are not getting rebuilt regularly in an automated fashion.

Can you please add one step to your CI pipeline and push the image also Docker Hub?

Thanks

Tobias

**Comment by jarpy** [comment]
This gets a bit weird because there are two meanings of "official" here.

1. The "official" images on Docker Hub were maintained by Docker Inc.
2. The newer "official" images are based on a completely different build (sharing no code) and are maintained by Elastic.

We (Elastic) don't have any plans to host images on the public Docker Hub right now, sorry.

**Comment by tmaier** [comment]
You could host it under elastic/elasticsearch, right?

I think this repo also exists, but is empty.

**Comment by xeraa** [comment]
> We (Elastic) don't have any plans to host images on the public Docker Hub right now, sorry.

To rephrase: This is not accidental, but a conscious decision. We are heavily driven by downloads (which version, which country, changes,...) and there is no way of getting this information from Docker Hub. Additionally, we were not too happy with Docker Hub's availability and performance and since we build heavily on those images, we needed a better solution.

To understand your use case better: What are you doing in your custom build and why does it have to happen automatically?

**Comment by franklinyu** [comment]
I saw this repository on Docker Hub: https://hub.docker.com/r/elastic/elasticsearch/

Is this managed by anyone in Elasticsearch? The username is trying to imply so.

**Comment by xeraa** [comment]
Yes, this is now mirroring our own registry and you are getting the same images. Thanks for pointing that out here!

**Comment by franklinyu** [comment]
But https://www.docker.elastic.co/ is still preferred for production right? For performance reason?
