### ISSUE TITLE
Should we recommend limiting memory if it affects VFS cache?

### ISSUE THREAD

**Issue by jarpy** [elastic/elasticsearch-docker#122]
In our documentation, we suggest setting a memory limit for Elasticsearch containers. However, Docker uses the `memory.limit_in_bytes` property of the kernel [Memory Resource Controller](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) to achieve this, which also appears to limit the amount of file cache that the process has access to.

File cache can be beneficial to Elasticsearch performance, so perhaps we should adjust our recommendation. We could either include a note about the limiting effect on file cache or remove the recommendation altogether.

**Comment by dliappis** [comment]
Good catch! My suggestion is to remove this from the docker-compose prod example and include an additional note item to explain the disadvantage with setting this; I think it's still worth to remind that it is possible to limit the mem e.g. for people with limited mem due to defaults in Docker for Mac/Docker for Windows who may accept a performance penalty.

**Comment by dliappis** [comment]
This has been tackled in the docs some time ago.
