### ISSUE TITLE
Install templates (index/query) at first start

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch-docker#134]
## Feature Description

Automatically install index/query templates at start time, found in a specific directory.

* Like mysql image (that execute SQL queries at first run)
* elasticsearch Docker container will be "self-ready" (not sure about this term ...)
* Ideal to distribute an image 100% configurable

I think a small script that wait ES ready, check a directory content (``/opt/template/index/``), loop files and PUT templates.

**Comment by zanematthew** [comment]
Isn't this best built with your app code? 

I'm interested in this as well, but I'd like to know what _best practices_ would be. Currently my app uses ES templates, however I have a script on the app side, that install the templates in ES.

I'm currently porting my local app, a VirtualBox to docker containers.

**Comment by ebuildy** [comment]
The best practice is "Docker image / container must be independent", so it has nothing about application.

Take mysql official image, you can provide a sql script that initialize the data-base, so it make sense to have the same behavior with elasticsearch, you want to have an elasticsearch ready for your business (with right index/search templates).

**Comment by xeraa** [comment]
IMO this feels like feature creep. And while this is a nice feature for test setups, it might be catastrophic for production use cases.

Our general recommendation for setup steps are short-lived containers — see our [stack-docker repo for an example](https://github.com/elastic/stack-docker/blob/master/docker-compose.yml#L115-L125). If you are using the base image of the Elasticsearch image you already have all the required parts available.

PS: MySQL might pick different tradeoffs since you need to configure databases there and you need a driver that speaks the right wire protocol.

**Comment by ebuildy** [comment]
yep you are right, but I see more people using Docker in dev/test than production, and they want something simple and ready to use.

And for people who use Docker in production, they rarely rely on no-custom image (in my experience).

**Comment by PierrickPuimeanChieze** [comment]
> And while this is a nice feature for test setups, it might be catastrophic for production use cases.

I am curious. What make this kind of feature potentially catastrophic ?

**Comment by jarpy** [comment]
I think @xeraa was thinking about scenarios where a test configuration might be accidentally started in a production environment. If the container has been given the ability to mutate data on start, it's possible to imagine scenarios where it will mutate real, live customer data in production by mistake.

**Comment by jarpy** [comment]
Doing that would require managing multiple asynchronous processes within a single container, since we'd have to start Elasticsearch in the "background", then have the loader process wait/poll until Elasticsearch is ready to handle the requests. Under the classical container model, we don't really want to be doing things like background'ing processes at all. "One process per container" and all that.

I'd argue that handling multiple asynchronous processes is the task of a container scheduler/orchestrator, not the task of a single container. We recommend running the loader process as a separate short-lived container. Your orchestrator (even if it's just Docker Compose) can then arrange to start the loader only when Elasticsearch is up and passing its healthcheck.

**Comment by veqryn** [comment]
I can only say that the official docker-hub images for MySQL and other databases/data-stores do this.  I doubt it goes against principles so much, otherwise the official images from the people who made docker would have this ability.

**Comment by xeraa** [comment]
> I can only say that the official docker-hub images for MySQL and other databases/data-stores do this.

Which doesn't mean that we agree with that. There's a reason why we manage our images separately — changing permissions on the bind mounted directory, testing (or the lack thereof),...

Anyway, I took a quick look what the official MySQL image is doing to load data and it's [wrapping the entrypoint in quite a bit of shell code to load data and do other things](https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh#L94-L214). I still don't think this is something the Docker image should do.

**Comment by rjernst** [comment]
As @xeraa and @jarpy illustrated here, this kind of additional features over our base products is something we tend to shy away from. Additionally, maintenance of the docker files for elasticsearch has moved to the [elasticsearch repo](https://github.com/elastic/elasticsearch). As we will be archiving this repository, I am going to close this issue.
