### ISSUE TITLE
`make` failed with 404 Not Found error

### ISSUE THREAD

**Issue by lag-linaro** [elastic/elasticsearch-docker#163]
* Docker image used
A clone of this repo

* Operating System
Ubuntu Linux

* `docker info` output
* `docker inspect NAME|ID` output
* `docker-compose --version`, if relevant
N/A

* Steps to reproduce
Just type `make`

[SNIP]

Step 8/28 : RUN curl -fsSL https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-alpha1.tar.gz |     tar zx --strip-components=1
 ---> Running in 3292364c1c79
curl: (22) The requested URL returned error: 404 Not Found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl -fsSL https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-alpha1.tar.gz |     tar zx --strip-components=1' returned a non-zero code: 2
Error response from daemon: No such image: docker.elastic.co/elasticsearch/elasticsearch-full:7.0.0-alpha1
Makefile:84: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by jarpy** [comment]
Oops. I thought this issue was in the `logstash-docker` repository.

The `make from-snapshot` target already exists here in `elasticsearch-docker`. My other comments still apply.

**Comment by lag-linaro** [comment]
Done. Thanks for the tip.

**Comment by jarpy** [comment]
Thank you. That's much easier to parse! 😃 

OK. So there's a couple of things happening here. From the references to "full" and "oss" versions of Elasticsearch, I can tell that you are still on the `master` branch of this repo. Since you want to build version `6.2.4`, [you need to check out the `6.2` branch](https://github.com/elastic/elasticsearch-docker#running-a-build).

The second thing is probably harder to fix. This line is interesting to me:

```
/usr/lib/go-1.8/src/runtime/asm_arm64.s:981 +0x4
```

From that, can I infer that you are trying to get this working on an ARM architecture machine? I suspect that your Docker, and specifically [docker-credential-helpers](https://github.com/docker/docker-credential-helpers) is either not set up correctly or simply has a bug on ARM.

I'm afraid I can't help much with that. This project is developed and tested exclusively on x86_64, which is also the only supported architecture for Elasticsearch itself. Having said that, this repository is mostly Python and Make, which should be fine on ARM if the underlying Docker components are working correctly. I don't want to discourage you from experimenting, but I do want to let you know that what you are trying _is_ kind of experimental.

**Comment by jarpy** [comment]
With that discovered, would you mind going back and adding your `docker info` output to the initial post? It could help others in the community find this thread if they hit a similar issue.

Thanks.

**Comment by jarpy** [comment]
Cool. So you can see that the images built:

```
Successfully built 3975789ab24c
Successfully tagged docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
```

...but the tests are failing because the test container doesn't appear to start.

Try starting a container from the images you built and see what happens.

**Comment by lag-linaro** [comment]
Seems fine after a couple of changes to the source and sysctrl system limit.

But the tests still fail:
https://gist.github.com/lag-linaro/3caf1fa1efe508b0f74e2fe15132eb40

**Comment by lag-linaro** [comment]
I believe *this* issue is now solved, closing.

Will open another which is more relevant.
