### ISSUE TITLE
Deploy ES by separating data node and master-eligible node

### ISSUE THREAD

**Issue by cloudmelon** [elastic/elasticsearch-docker#184]
Hi, I am deploying ES with Docker, but I would like to deploy 3 dedicated master node and a couple of data node in the cluster ( huge cluster can be scaled up to100 instances ) , is there any way to deploy a master node image and a data node image ?  Data node and master node can municate with each other via network call, so load balancer can send the request directly to data node cluster ? Thanks

**Comment by xeraa** [comment]
The image is the same for all nodes. You just need to configure the role of the node — either via environment variables or by bind mounting a custom configuration, see the [Elasticsearch Docker docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods).

For example for a dedicated master-eligible node you [should add the settings](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/modules-node.html#master-node):

```
node.master: true 
node.data: false 
node.ingest: false 
search.remote.connect: false
```

BTW instead of a load balancer you might want to add [coordinating only nodes](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/modules-node.html#coordinating-only-node).

**Comment by xeraa** [comment]
Closing since any further discussion around this should probably be on https://discuss.elastic.co
