### ISSUE TITLE
Elasticsearch latest not available

### ISSUE THREAD

**Issue by eddiejaoude** [elastic/elasticsearch-docker#215]
## Bug Description

Following the docs on DockerHub and ElasticSearch website, the latest is not available, output...

```shell
➜  docker pull elasticsearch
Using default tag: latest
Error response from daemon: manifest for elasticsearch:latest not found
```

<img width="1290" alt="screenshot 2018-11-16 09 22 04" src="https://user-images.githubusercontent.com/624760/48607387-77841d00-e981-11e8-8877-e2c1ded9ea06.png">

**Comment by eddiejaoude** [comment]
Specifying the latest version works fine, but the latest is not selected by default 

```shell
docker pull elasticsearch:6.5.0
6.5.0: Pulling from library/elasticsearch
aeb7866da422: Pull complete 
81639a7b2dd2: Pull complete 
e19ec3fb86be: Pull complete 
da4a438e18a0: Pull complete 
a67c58efe429: Pull complete 
13fe2c49e9dd: Pull complete 
162a1c0b34b0: Pull complete 
64d1055a351e: Pull complete 
Digest: sha256:81a75d058b2ca52be06915eed43343c4e289d5463265de8446fbd77f8e170327
Status: Downloaded newer image for elasticsearch:6.5.0
```

**Comment by eddiejaoude** [comment]
> Note: Pulling an images requires using a specific version number tag. The latest tag is not supported.

I just saw this further down the page

**Comment by jethr0null** [comment]
Apologies for any confusion. Unfortunately, there isn't a mechanism for updating the sample pull command to reflect a version tag (or the need to specify one) in the Docker Hub UI. Calling out in the requirement in the documentation is the best option available at the moment. Thanks so much for the feedback and your understanding.

**Comment by tianon** [comment]
@jarpy I think we talked about that a bit and came to the conclusion that none of the options there were really great -- we could embed a specific version, but that's likely to be outdated very quickly, or we could use a generic placeholder (that won't work in a direct copy-paste as-is), like `elasticsearch:tag` (which we've used on other images, like `cassandra`: https://hub.docker.com/_/cassandra/)

I think it would probably be possible to add a new `%%FIRST-TAG%%` placeholder that could be used, but I'm a tad wary of that (since the examples then likely won't have been checked for compatibility on every tag bump, but will be using a tag that's specific enough to seem to imply that it ought to work).

cc @yosifkit

**Comment by guice** [comment]
`:latest` tag used to work. 

At some point, it was removed. We didn't notice until recently when a new developer attempted to run a `docker-compose up`. Other developers with existing images do have a pre-existing `:latest` tag.

It should also be noted you're missing other tags: `:6` and `:6.5`

`:latest` is useful in understanding what's the official latest image: 5 or 6? You're missing a `:6` tag and `:6*-alpine`, so it is still `:5`?

**Comment by xeraa** [comment]
As long as the image behind `docker pull elasticsearch` was maintained by Docker Inc and not Elastic, they did provide a `:latest` tag. That was the case until the end of 5.x, then the image was deprecated, and later on we took over.

We intentionally don't provide `:latest`, `:6`, or `:6.5` because we consider it a bad practise — see part of the discussion above and various other issues in this repo.
You can always follow the latest releases in https://github.com/elastic/elasticsearch-docker/releases

**Comment by tanerozel** [comment]
> Specifying the latest version works fine, but the latest is not selected by default
> 
> ```shell
> docker pull elasticsearch:6.5.0
> 6.5.0: Pulling from library/elasticsearch
> aeb7866da422: Pull complete 
> 81639a7b2dd2: Pull complete 
> e19ec3fb86be: Pull complete 
> da4a438e18a0: Pull complete 
> a67c58efe429: Pull complete 
> 13fe2c49e9dd: Pull complete 
> 162a1c0b34b0: Pull complete 
> 64d1055a351e: Pull complete 
> Digest: sha256:81a75d058b2ca52be06915eed43343c4e289d5463265de8446fbd77f8e170327
> Status: Downloaded newer image for elasticsearch:6.5.0
> ```

Thank you  very good work

**Comment by mathieuduperre** [comment]
same problem here. had to specify 6.5.0, as latest was not selected by default and even stating selected did not get me anything.

**Comment by adeng-wc** [comment]
> Specifying the latest version works fine, but the latest is not selected by default
> 
> ```shell
> docker pull elasticsearch:6.5.0
> 6.5.0: Pulling from library/elasticsearch
> aeb7866da422: Pull complete 
> 81639a7b2dd2: Pull complete 
> e19ec3fb86be: Pull complete 
> da4a438e18a0: Pull complete 
> a67c58efe429: Pull complete 
> 13fe2c49e9dd: Pull complete 
> 162a1c0b34b0: Pull complete 
> 64d1055a351e: Pull complete 
> Digest: sha256:81a75d058b2ca52be06915eed43343c4e289d5463265de8446fbd77f8e170327
> Status: Downloaded newer image for elasticsearch:6.5.0
> ```

Thank you very good work

**Comment by rjernst** [comment]
The lack of a `latest` tag is now mentioned in a note on how to use the image.

Additionally, maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. As we will be archiving this repository, I am going to close this issue.
