### ISSUE TITLE
Update ES version to 5.1.2

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch-docker#23]
## Feature Description

Update ES version to 5.1.2.  The current docker image is still pointing to ES version 5.0.1.

**Comment by jarpy** [comment]
It looks like @dliappis pushed `:5.1.2` to the registry. Thank you for catching this, Sir!

`:5.1.1` was already there though, so it's odd that you are getting `:5.0.1`. I suspect that you are referencing the `:latest` tag? We no longer publish a `:latest` tag, so I guess if you have a local `:latest` that you are still referencing, it will continue to point to whichever version was pulled when `:latest` was still a thing on the registry.

That's a bit of a trap, sorry about that. We removed `:latest` precisely because it is ambiguous. We want everyone to get exactly the version that they ask for, no newer, and in your case, no older!

**Comment by sherry-ger** [comment]
Bah, I missed that! Thank you!
