### ISSUE TITLE
Unable to pre-load data into ES container during build

### ISSUE THREAD

**Issue by Schachte** [elastic/elasticsearch-docker#238]
## Bug Description

I've specified the volume to mount to ES data directory within the container. 

```
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
```

Unfortunately, this doesn't load the data into any index when booting the container. I can see the json data was transferred correctly into the container though. What is the reasoning for this? I can't seem to automate loading _any_ data at all.

**Comment by xeraa** [comment]
Just to be sure we are talking about the same thing here: You have JSON files mounted via `./elasticsearch/data:/usr/share/elasticsearch/data` and would expect them to be loaded into Elasticsearch? Unfortunately it doesn't work like that. Neither can Elasticsearch work directly on JSON files (data needs to be indexed and the result is what is being stored in this data directory) nor does it load JSON files automatically.

Since you can do all the data manipulation with HTTP requests and don't need a dedicated client, we are not trying to abstract away any data loading (unlike some other Docker containers of datastores).

**Comment by Schachte** [comment]
Gotcha. What's the recommended way of automatically loading data into ES in docker?

**Comment by Schachte** [comment]
Got it working by just indexing the data over curl and just adding the indexed data into my repo so other devs get the same data.
