### ISSUE TITLE
Could not register mbeans access denied

### ISSUE THREAD

**Issue by jackhold** [elastic/elasticsearch-docker#28]
I am getting the following error when trying to run Elasticsearch with the --user option
main ERROR Could not register mbeans java.security.AccessControlException: access denied

Docker run command:
docker run -d --name ES --user ES:ES  --log-opt max-size=1g -m 3G --cpus="1.0" -v "$PWD/esdata":/usr/share/elasticsearch/data -p 9200:9200 elasticsearch

if i just remove the --user option the error don't show up. 

it's running on a Debian host and everything is updated to the latest version.

**Comment by dliappis** [comment]
@jackhold When you specify just `elasticsearch` as the docker image you are not using the official image of Elastic, described in https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html. Instead you are using an image provided by [Docker Hub](https://github.com/docker-library/elasticsearch).

To use the image maintained by Elastic, you need to use `docker.elastic.co/elasticsearch/elasticsearch:5.2.1` or which ever release you wish to target.

Please try going through the documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) to see examples of how to use the Elastic maintained Elasticsearch Docker image.

As an aside topic, I am not sure what you are trying to achieve by setting the [--user option](https://docs.docker.com/engine/reference/run/#user). AFAICS the image shipped by Docker Inc. has an elasticsearch user and group (uid:gid 105/108) but starts as root and then switches to the elasticsearch user in order to mutate your local host dir to match the uid:gid needed by the elasticsearch user in the image.

**Comment by jackhold** [comment]
now that you are saying it... i have worked with ES in docker for a little over 3 weeks and haven't realised there where 2 "official" docker images for Elasticsearch.. I will take a look into the docker image you are releasing just to compare them.
 
The reason i want to change the user is because the uid and gid is already in use on the host machine so all the files the Elasticsearch is dumping can be accessed by a user that don't need to access them, and when you are debugging on the host machine it's just nice to have a user name that reflects the process.

so yes it might be a more nice to have then need 2 have but i cant see a reason why it shouldn't be possible.

**Comment by dliappis** [comment]
Just to be clear the official image that Elastic supports is the one related to this repo and [the documentation mentioned earlier](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). Eventually the one from Docker Inc. will be deprecated, some [details here](https://github.com/docker-library/elasticsearch/pull/160).

Regarding the user issue:

In general most Docker images run the main process as a non root user (which is a good security practice). For example `docker.elastic.co/elasticsearch/elasticsearch:<release>` runs elasticsearch as `1000:1000`.

Altering the user this runs as is going to create problems as other dirs under `/usr/share/elasticsearch` are owned by `1000:1000`.

Instead you should consider using a [named volume](https://success.docker.com/KBase/Different_Types_of_Volumes) to store your data, with something like:

`$ docker run -v esdata:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:5.1.2`

This will create a docker volume, shown with:

```
$ docker volume ls
DRIVER              VOLUME NAME
local               esdata
```

that will persist even if you terminate the instance.
If you _really_ want to see where it resides on your localfilesystem you can find the path with `docker volume inspect esdata`.

**Comment by jackhold** [comment]
Thanks the link to the discussion, looking at the date's it's more understandable that i didn't see that the image docker is distributing isn't in collaboration  with you.. and from what i can read i am goner switch to you're image.

The problem with not having the option to switch the user id is not just the files but if you wanner debug on the host machine and have a user named bob with the UID 1000 all the elasticsearch processes will show up as bob. 

but like i said it's a minor problem that i can work around by making my own docker file that changes the userid and the permissions of the folders.

thanks again for you're time and the extra information about the docker image.

**Comment by dliappis** [comment]
I am glad the comments were of use to you! Closing this issue.
