### ISSUE TITLE
Environmental Variables

### ISSUE THREAD

**Issue by lhopki01** [elastic/elasticsearch-docker#33]
Config options are passed in as environmental variables like -e "cluster.name=mynewclustername" but this causes issues with Kubernetes and many other places as they don't accept environmental variables with . in the name.  This should be changed to match standards and use _ instead.

As far as I can tell the only thing that accepts environmental variables with . in the name is docker.

**Comment by dliappis** [comment]
Thank you for the feedback!

We will be consolidating the way to pass config options via docker env vars so that it's consistent across all our docker images, so stay tuned.

FYI if you haven't seen [this issue](https://github.com/kubernetes/kubernetes/issues/2707#issuecomment-285309156) seems that k8s may get the same functionality as docker and as per the [POSIX spec](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) be tolerant for those.

**Comment by joan38** [comment]
This is now supported in Kubernetes 1.8
Should we close this issue?

**Comment by dliappis** [comment]
Agreed @joan38 . Kubernetes 1.8 supports this and if stuck at an earlier version, you can use configuration option D. [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_d_override_the_image_8217_s_default_ulink_url_https_docs_docker_com_engine_reference_run_cmd_default_command_or_options_cmd_ulink).

**Comment by lhopki01** [comment]
Agreed.  Thanks.
