### ISSUE TITLE
Windows Container

### ISSUE THREAD

**Issue by dumonjorne** [elastic/elasticsearch-docker#67]
## Feature Description
Will there be an official elasticsearch-docker container based on the windows nano server 2016 image?

**Comment by dliappis** [comment]
This has been discussed in https://github.com/elastic/elasticsearch-docker/issues/61; unfortunately it is not on the immediate road map yet.

Having said that, given the availability of [Docker EE for Windows Server 2016](https://www.docker.com/docker-windows-server) -- which I assume your use case is based on -- we certainly have it on our radar so stay tuned.

**Comment by MonDeveloper** [comment]
We are intereset too, in addiction to the "nano" version (which is pretty tight reduced versione of Windows Server kernel) we are also interested into the "core" version.

Thanks in advance!
mM

**Comment by sixeyed** [comment]
@dliappis I have working Docker images based on Windows that could be used as a starting point - [Dockerfile based on Windows Server Core](https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/Dockerfile), and [Dockerfile based on Nano Server](https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/Dockerfile.nanoserver).

Happy to help with the Windows side when you folks pick this up.

**Comment by dumonjorne** [comment]
@sixeyed Thanks for this!

**Comment by dynamicmoodz** [comment]
@sixeyed - Can you share the DockerFile for Nano server?

**Comment by sixeyed** [comment]
Here's a working example: https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/nanoserver/Dockerfile

**Comment by MonDeveloper** [comment]
@sixeyed on 18 Sep:
> @dliappis I have working Docker images based on Windows that could be used as a starting point - Dockerfile based on Windows Server Core, and Dockerfile based on Nano Server.
Happy to help with the Windows side when you folks pick this up.

links seem to be broken, could you refresh them?

Thanks in advance

**Comment by valleen** [comment]
Thank you for your example!
I've got a serious issue running any elastic with ingest-attachment docker image on the windows docker (not only yours). (it works fine on when I switch to linux and use official images)

Most of my files cannot be ingested and get this socket error:
`Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)`

**Comment by sixeyed** [comment]
@valleen  - I haven't seen any issues with Elasticsearch running in Windows containers. You could try [this Dockerfile which is based on Windows Server Core](https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/windowsservercore/Dockerfile) - and see if you still get the issue?

**Comment by sixeyed** [comment]
Curious if this is still something you're looking at? I'm working on the 2nd edition of my [Docker on Windows](https://www.amazon.com/Docker-Windows-Elton-Stoneman-ebook/dp/B0711Y4J9K/) book, and it would be great to use official Elastic images rather than my own custom ones. For reference, this is my latest [Dockerfile for Elasticsearch on Windows Server Core](https://github.com/sixeyed/dockerfiles-windows/blob/master/elasticsearch/windowsservercore/Dockerfile).

**Comment by deepaklaller1988** [comment]
i am facing elastic search on window docker

**Comment by sixeyed** [comment]
No problem :) I've moved things around - here's where all the [Windows Elasticsearch images are](https://github.com/sixeyed/dockerfiles-windows/tree/master/elasticsearch)

**Comment by rjernst** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/43608 for future discussion on this issue.
Maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. As we will be archiving this repository, I am going to close this issue.
