### ISSUE TITLE
config cors setting not working?

### ISSUE THREAD

**Issue by gordontw** [elastic/elasticsearch-docker#73]
I setup a standalone elasticsearch using elasticsearch:alpine.
Try to enable cors setting in /usr/share/elasticsearch/config/elasticsearch.yml
```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"
```
then restart this container.
curl --head http://localhost:9200, the result is
```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 327
```
No CORS header, is it right?

**Comment by dliappis** [comment]
@gordontw Just a quick comment, `elasticsearch:alpine` is the image on [Docker Hub](https://hub.docker.com/_/elasticsearch/), the images in this repo are hosted under [Elastic's own registry](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html).

You could try bind mounting your customized elasticsearch.yml (or specify parameters with env vars) instead of needing to manually edit the file inside the container and restart it.

AFAICS this looks like an ES config question not directly related to Docker, discuss.elastic.co is a better place to ask ES config related questions.
