### ISSUE TITLE
:latest tag for all images

### ISSUE THREAD

**Issue by jklare** [elastic/elasticsearch-docker#75]
## Feature Description

Hi,

is it possible to also include a :latest tag (like it was in the old dockerhub repo here https://hub.docker.com/_/elasticsearch/) for the newest container build and published? Of course this would also be great for the other containers published, but i am not sure if i should open an issue for all of them?

Cheers,
Jan

**Comment by drewr** [comment]
Thanks for the request, @jklare but we intentionally don't create a `latest` tag. We want users to always be considering the version they're pulling to avoid the inevitability that `latest` will no longer be what they expect. It's too easy to be lulled into the convenience only to be surprised later by running a version that's incompatible with their environment. If you would like to always get the latest version, you would need to automate it locally.

**Comment by bigwheel** [comment]
I think `latest` tag is worth existing.

1. Experienced engineer normally know importance of pinned version in product developing, he/she must not use latest tag there.
2. It is useful for elasticsearch newbie. He/she don't know what version is latest release. If he/she knows docker well, he/she starts to use elasticsearch only with repository url ( https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_security_note ).
    * You must say lastest release version is also written in that page, but document update delays sometimes and, in addition, elasticsearch document has version itself(for 5.6 document, for 1.4 document). It confuses newbie. In contrast, a repository path and latest tag is a standard solid way to pull latest image.
3. latest tag can be used in CI. If I have to provide only latest elasticsearch version support for my product (e.g, library), I must refer latest tag in CI process. Without latest tag, I have to change version tag manually in each version update.

**Comment by xeraa** [comment]
Thanks for providing feedback — we really value the input from the community, so please keep sharing ideas and concerns :)

However, I disagree on this one:

> 1. Experienced engineer normally know importance of pinned version in product developing, he/she must not use latest tag there.

IMO that's also the reason why we should not provide a `:latest` tag — it's simply not a good idea and we shouldn't set anybody on the wrong path.

> 2. It is useful for elasticsearch newbie. He/she don't know what version is latest release. If he/she knows docker well, he/she can start to use elasticsearch only with repository url ( https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_security_note ).
> You must say lastest release version is also written in that page, but document update delays sometimes and, in addition, elasticsearch document has version itself(for 5.6 document, for 1.4 document). It confuses newbie. In contrast, a repository path and latest tag is a standard solid way to pull latest image.

You can literally copy the right command from the documentation. Also [https://www.docker.elastic.co](https://www.docker.elastic.co) shows you the possible options and again provides copy & paste.
If you cannot be bothered with this, I'm afraid you will have a bad time with our images. We have certain requirements around permissions of your data directory,... and you really should read the documentation and understand what's going on.

> 3. latest tag can be used in CI. If I have to provide only latest elasticsearch version support for my product (e.g, library), I must refer latest tag in CI process. Without latest tag, I have to change version tag manually in each version update.

That is like adding a lottery to builds. Most integration tests suffer from overly brittle results already — you wouldn't want to add more variability there.
You might have a very specific use case, but most people will either support a specific version or a set of versions (and not just latest).
And once we release a new major version, there's a chance that we will break your tests. If it's more complicated or you don't immediately have time for a fix, your CI tests will be broken for some time. I don't think an external dependency should be able to do that. Personally, I'd strongly prefer the version upgrade and the required changes in a PR.

> 4. latest tag is default tag in docker command (e.g, https://docs.docker.com/engine/reference/commandline/tag/ ). Fighting with docker default is not smart.

I think default is too strong. Since the version is optional this is the only thing that can be the default. This doesn't mean that it's a great idea though. Quoting from https://docs.docker.com/develop/dev-best-practices/: "When building images, always tag them with useful tags which codify version information, intended destination (`prod` or `test`, for instance), stability, or other information that will be useful when deploying the application in different environments. Do not rely on the automatically-created `latest` tag."

Related to that, most dependency management systems don't allow a latest tag or even removed it. For example [Maven removed `LATEST` and `RELEASE`](https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-PluginMetaversionResolution) for the sake of reproducibility.

**Comment by sirudog** [comment]
@xeraa I agree with you. 
Yet there is one scenario which I am actively investigating and would like to ask for your advice about: 
how could I be notified about new releases of elastic.co products? 
My idea was to use a tool like [anchore-engine](https://github.com/anchore/anchore-engine) and subscribe to tag updates of `docker.elastic.co/elasticsearch/elasticsearch-oss:latest` or `docker.elastic.co/kibana/kibana-oss:latest`
This tool is capable of watching these tags, and if the latest tag would be used, anchore-engine could trigger a web hook to send a hipchat message to devops team, or even rebuild my custom docker images based on any of the watched images, and make them ready for verifying that the version update has not broken anything in my solutions.
