### ISSUE TITLE
vm.max_map_count [65530] is too low in Docker-Windows.

### ISSUE THREAD

**Issue by jlruizmlg** [elastic/elasticsearch-docker#92]
Hello all, 

Im trying to run elasticsearch 5.5.0 in windows with docker, but i'm having a issue:

```
elasticsearch_1  | ERROR: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

Any option to avoid this error and let elasticsearch run normally?

Thanks!!

**Comment by jlruizmlg** [comment]
Hi guys, i will answer myself:

```
docker-machine ssh
sudo sysctl -w vm.max_map_count=262144
exit
```

Thanks!

**Comment by dliappis** [comment]
Thanks @jlruizmlg ; this is needed when using `docker-machine` for Windows as opposed to Docker for Windows. Some clarifications between those two in https://forums.docker.com/t/how-can-i-ssh-into-the-betas-mobylinuxvm/10991/8.

I took a note to update the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode) to mention OSX+Windows with Docker Toolbox instead of just OSX with Docker Toolbox where this procedure is explained.

**Comment by khusseini** [comment]
I'm getting this error for Linux Mint 18 and image tag `5.5.1`

**Comment by dliappis** [comment]
@khusseini If you are not running elasticsearch [in the dev mode](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode) you'll _need to_ set the vm_max_map_count as documented in the important note in the [installation docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode).

**Comment by khusseini** [comment]
@dliappis, ah alrighty, I skimmed the page a bit too fast

**Comment by dliappis** [comment]
No worries @khusseini :+1:
